module Gemjars
  module Deux
    class Binscript
      attr_reader :spec, :bin_file_name
      
      def initialize spec, bin_file_name
        @spec = spec
        @bin_file_name = bin_file_name
      end

      def to_s
    <<-TEXT
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application '#{spec.name}' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = "#{Gem::Requirement.default}"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\\A_(.*)_\\z/
    version = $1
    ARGV.shift
  end
end

gem '#{spec.name}', version
load Gem.bin_path('#{spec.name}', '#{bin_file_name}', version)
TEXT
      end
    end
  end
end

